package com.schilling3003.relay.audio

/**
 * Plays PCM/audio generated by a synthesizer and handles audio focus.
 */
interface AudioPlayer {
    suspend fun play(audio: ByteArray, sampleRateHz: Int = 16_000)
    suspend fun stop()
    fun release()
}
